### ISSUE TITLE
UTF-8 encoding does not work

### ISSUE THREAD

**Issue by KSchreyer** [jxcore/jxm#20] opened 2015-06-05 10:31 UTC
Hi,
I'm currently evaluating JXM as a messaging backend for our Online-Campus. Unfortunately it seems that the UTF-8 encoding for the messages does not work correct. When I send german umlauts (e.g. ä, ö, ü), I receive hieroglyphs.

You can re-produce this with your server-side-subscription example. Changing the "Hello from browser" message in index.html to "Hello from browser ä ö ü Ä Ö Ü", then reload the webpage and click the "start"-Button and you will see that the characters are not getting displayed correct.

By the way two more questions:
- How stable is JXM at the moment? I know JXCore is tagged as beta, but would you already use JXM in a production system (knowing that the API can change in the future)?

- What are you're plans for the Java-Client? Will it receive ongoing support and development?

Thanks in advance for your answers,
Kai

**Comment by plika** [comment] 2015-06-05 12:41
> How stable is JXM at the moment? 
I would say battle tested stable. It is possible that there are minor issues around but from the point of uptime and persistent, it should serve smoothly.

> What are you're plans for the Java-Client? Will it receive ongoing support and development?
Yes

As for the bug. I'm not sure. I couldn't reproduce it on my first shot. I will try to reproduce it on a simple project.

**Comment by KSchreyer** [comment] 2015-06-05 13:10
I'm using jxm version 0.3.7 from the npm registry.

**Comment by KSchreyer** [comment] 2015-06-05 13:13
And node version 0.10.33.

**Comment by KSchreyer** [comment] 2015-06-09 16:30
I've additionally tried the following on my (Linux based) development machine, with the same result:
 - Set the server "encoding" configuration explicitly to "UTF-8"
 - Updated node to 0.10.38
 - Tried jx 0.3.0.1 instead of node

I could also reproduce this on a Mac OS X MacBook, using node 0.10.33. The only common what those two machines have, is that their locale is set to "de_DE.UTF-8".
For the meantime, I Base64-Encode and -Decode each message. This works for now, but can only be a temporary workaround.

Do you have any ideas, or suggestions?

**Comment by ktrzeciaknubisa** [comment] 2015-06-09 17:25
@KSchreyer Are you having this on JavaScript or Java client?

**Comment by ktrzeciaknubisa** [comment] 2015-06-09 17:32
Ok, I've got this in browser. Interesting, that e.g. Chinese and Russian gets displayed correctly :)

> Hello from browser German: � � � � � �
Hello from browser Chinese: 齈龘墻 儮嬼懫 瀷
Hello from browser Russian: Эа эжт

**Comment by KSchreyer** [comment] 2015-06-09 20:24
Yes, I have this problem in the browser with the JavaScript client. Chinese and Russian are working for me too. Strange that it does work for Chinese and Russian, but not for German.

**Comment by ktrzeciaknubisa** [comment] 2015-06-11 09:06
Here is what I've noticed so far:

1. Only V8 has problem with your chars. If you try SM build, it should work, as it worked for me.
2. It looks like the cause is that V8's `querystring.unescape()` is not compatible in this case with browser's `escape()`. 
3. Since `escape()` and `unescape()` seems to be depreciated, I've made a quick test and replacing them into `encodeURIComponent()` and `decodeURIComponent()` respectively made V8 work properly with your characters. But this needs more testing (with other languages too), so I'm not including this yet. 

That is, for now your workaround (apart from base64) would be to either use SM or replace the method I've mentioned at least in `jxm/backend/jx_browser_client.txt`.

**Comment by KSchreyer** [comment] 2015-06-11 13:10
Hi,
I replaced the methods in jxm/backend/jx_browser_client.txt. After that, it works for most of the characters. But when you try to send a percent sign (%), you will get an "URIError: URI malformed" in the following line:
jxcore.Notify(ee, decodeURIComponent(ev.data));

**Comment by ktrzeciaknubisa** [comment] 2015-06-11 13:21
Thanks for the update. We'll keep it in mind when applying the fix. If you'll have any other observations - please let us know!

**Comment by ktrzeciaknubisa** [comment] 2015-06-19 19:50
I've found the reason. It seems like for websockets the message is sent from server to client already unescaped, and when the client's browser tries to unescape it again - there you get your error. 

This will be fixed next days.

**Comment by ktrzeciaknubisa** [comment] 2015-06-20 14:34
Hi @KSchreyer. I've posted an update f4dacabc9e9ac98029ff53f7f2c1dd55203f4bb4 to master branch. Could you please check if that solves your encoding problems? Also percent sign or other special chars should not disturb any more. 

As a reminder - we're talking here about JXcore's V8 build.

**Comment by KSchreyer** [comment] 2015-06-20 15:01
Hi,
I will try to check this on Monday. Can you please also update the jxm package at npmjs.org to version 0.3.8?

Thanks,
Kai

**Comment by ktrzeciaknubisa** [comment] 2015-06-21 12:10
We'll do that after few more tests and also your feedback :)

**Comment by KSchreyer** [comment] 2015-06-22 12:21
I applied the changes of update [f4dacab](https://github.com/jxcore/jxm/commit/f4dacabc9e9ac98029ff53f7f2c1dd55203f4bb4) and it works for me now. Also the test string `°!"§$%&/()=?è+*~#'äöüÜÖÄ-_.:;,µ²³` was successfully transmitted.

**Comment by ktrzeciaknubisa** [comment] 2015-06-22 12:31
Thank you! Which browser are you using? Did you try other browsers too?

**Comment by KSchreyer** [comment] 2015-06-23 10:22
Tested with the following browsers:
* Google Chrome 43
* Firefox 38
* Safari 8.0.6
* Opera 30
* IE 8
* IE 11

**Comment by obastemur** [comment] 2015-06-23 11:41
lets release then ?

**Comment by ktrzeciaknubisa** [comment] 2015-06-23 12:06
I think it's fine. I've also checked on android stock browser. Tested both SM and V8.

**Comment by ktrzeciaknubisa** [comment] 2015-06-23 12:13
Or let's wait a while more. The Java client should be checked, too.

**Comment by ktrzeciaknubisa** [comment] 2015-06-23 14:34
OK. Java client updated with b37fc3d8c3b2db9cb01354f5f1616d0d1b4ad0fd and tested. Also Java <--> Browser. I think we are ready for release 3.0.8. Thanks @KSchreyer for help!

**Comment by KSchreyer** [comment] 2015-07-20 10:01
Can you please also update the package at npmjs.org?

Thanks,
Kai

**Comment by obastemur** [comment] 2015-07-20 11:12
published.

**Closed by obastemur** 2015-07-20 11:12 UTC
